readme.md, standalone/Dockerfile, standalone/docker-entrypoint.sh, standalone/nginx/default.conf, ui-only/nginx/templates/default.conf.template
The web UI is served as static content from an nginx webserver. All api requests are proxied to the joinmarket server, but access should be limited as some unauthenticated endpoints contain sensitive information. It seems that the easiest way to keep serving the ui as static files would be Basic Authentication from nginx.
This change adds Basic Authentication to the nginx setup which can be controlled by environment variables `APP_USER` and `APP_PASSWORD`. ~~If no user and password is given, `joinmarket` is used as default user with a generated password logged to stdout~~ Providing these env variables is mandatory.
The current solution only works in conjunction with https://github.com/joinmarket-webui/joinmarket-webui/pull/102
=> feat: add basic auth to standalone

standalone/docker-entrypoint.sh, test/lint/lint-shell.sh, ui-only/jmwebui-entrypoint.sh
Add a shellcheck script (taken from [bitcoin-core](https://github.com/bitcoin/bitcoin/blob/master/test/lint/lint-shell.sh)) and resolve warnings.
```
In standalone/docker-entrypoint.sh line 4:
export JM_onion_serving_host="$(/sbin/ip route|awk '/src/ { print $9 }')"
^-------------------^ SC2155: Declare and assign separately to avoid masking return values.
In standalone/docker-entrypoint.sh line 33:
while read p; do
^--^ SC2162: read without -r will mangle backslashes.
In standalone/docker-entrypoint.sh line 39:
sed -i 's/autostart=false/autostart=true/g' $file_path
^--------^ SC2086: Double quote to prevent globbing and word splitting.
In standalone/docker-entrypoint.sh line 43:
done <$AUTO_START
^---------^ SC2086: Double quote to prevent globbing and word splitting.
In …
```
=> fix: resolve shellcheck warnings

standalone/Dockerfile
Re-adds `vim` and `ps` to `standalone` container.
They have been removed in order to decrease the image size, but they are needed in case anything unexpected happens.
=> devel: add vim and ps to standalone

standalone/supervisor-conf/jmwalletd.conf
From [supervisord docs](https://supervisord.org/configuration.html?highlight=autorestart):
> autorestart   Specifies if supervisord should automatically restart a process if it exits when it is in the RUNNING state. May be one of false, unexpected, or true. If false, the process will not be autorestarted. 
Default is `unexpected` so services are restarted if they do not exit cleanly. However, `jmwalletd` exited "cleanly" sometimes during testing. Not restarting it would force users to restart jmwalletd manually, which is.. suboptimal for non-power users. 
There is a case for restarting it even without the mentioned behaviour above.
What do you think? Is this a reasonable approach?
=> fix: autorestart jmwalletd

.env, readme.md, standalone/Dockerfile, standalone/nginx/default.conf, ui-only/jmwebui-entrypoint.sh, ui-only/nginx/templates/default.conf.template
Companion PR for websocket support. See [related issue in the UI repo](https://github.com/joinmarket-webui/joinmarket-webui/pull/122).
TODO:
Noteably changes:
- Proxies all request to `/jmws` to backend server on port `28283`.
- Use `upstream` directive and add `keepalive` flag - by default, nginx opens a new connection to an proxy server for every new incoming request. Also add `proxy_http_version 1.1` as recommended.
> By default NGINX uses HTTP/1.0 for connections to upstream servers and accordingly adds the `Connection: close` header to the requests that it forwards to the servers. The result is that each connection gets closed when the request completes, despite the presence of the `keepalive` directive in the `upstream{}` block. [...] Version 1.1 is recommended for use with …
=> Proxy websocket connection

readme.md, standalone/Dockerfile, standalone/default.cfg, standalone/docker-entrypoint.sh
Closes #24 and #4.
Instead of creating a default config file by executing `python wallet-tool.py generate` during install, a default config file is copied into the container. This config file is a copy of the generated file (by v0.9.5) with 2 adaptions:
- use onion irc servers (#24)
- define `max_cj_fee_rel` and `max_cj_fee_abs` (#4)
#24: The current default config (as of v0.9.5) uses clearnet irc connections. The adapted config file added with this PR uses their respective onion addresses.
#4: `max_cj_fee_rel` and `max_cj_fee_abs` are not defined in the default config (as of v0.9.5). However, they are needed to invoke a taker operation via jmwalletd's api. Default values have been introduced in order to remove the handling for commented out variables, and to emphasize that these values …
=> Default config

standalone/default.cfg
Closes #31. 
Update to the default config needed for the update to JM v0.9.6. Merge after #30 
This config is currently used in all node integrations and will override any user adaptions.
[Section `[MESSAGING:onion]`](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/release-notes/release-notes-0.9.6.md#new-p2p-onion-messaging-channels-with-directory-nodes) is new and needed for [onion message channels](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/onion-message-channels.md).
Amount of [default active irc servers](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/044bef6fffd9d33a1a170ccdec82b9fb48c65df3/jmclient/jmclient/configure.py#L191-L238) reduced from 3 to 2.
Q: Should we enable the third irc server?
[The irc …
=> config: update to default config for v0.9.6

standalone/nginx/default.conf, ui-only/nginx/templates/default.conf.template
Some requests can take quite a long time, e.g. `/create` can take minutes.
Increasing the timeout to 5min seems to be appropriate as of now.
=> fix: increase api request timeout from 60sec to 5min

ui-only/Dockerfile
Update nginx from `v1.21.6` to `v1.23.0` in ui-only.
No other changes where made.
>  incorporating new features and bug fixes from the mainline branch  — including hardening against potential requests smuggling and cross-protocol attacks, etc.
See the full [changelog](https://nginx.org/en/CHANGES)
=> build: update nginx from `v1.21.6` to `v1.23.0` in ui-only

readme.md, standalone/jam-entrypoint.sh, standalone/nginx/default.conf
Resolves #42.
Before this commit, basic authentication was mandatory and enabled by default. Users had to provide env vars `APP_USER` and `APP_PASSWORD`.
After this commit, basic authentication will only be enabled when `APP_USER` has a non-emtpy value. If `APP_USER` is given, `APP_PASSWORD` is mandatory.
=> feat: opt-in for basic authentication

standalone/Dockerfile, standalone/autostart, standalone/jam-entrypoint.sh, standalone/supervisor-conf/tor.conf, standalone/torrc
Closes #43.
This PR adds Tor to the `standalone` image. 
Before this PR, an external container has been necessary to connect to IRC or to the directory nodes.
After this PR is applied, the image lives up to its name and is truly "standalone", meaning: No external dependencies. A Tor daemon will be started at the startup of the container.
The changes in this PR are up to debate and every input or suggestion is highly appreciated.
This PR can be tested by following the instructions in [joinmarket-webui/#396 ](https://github.com/joinmarket-webui/joinmarket-webui/pull/396). A [build of this branch](https://github.com/joinmarket-webui/joinmarket-webui-docker/pkgs/container/joinmarket-webui-dev-standalone/28950781?tag=dev-with-local-tor-from-repo) has been made available as docker image, which …
=> dev: add tor from repo to standalone

standalone/nginx/default.conf, standalone/supervisor-conf/ob-watcher.conf
Serving the orderbook via nginx by passing requests to ob-watcher.py daemon.
Related to https://github.com/joinmarket-webui/joinmarket-webui/pull/422.
- Checkout this branch and build the standalone docker image locally with 
```sh
docker build --label "local" \
--build-arg JM_UI_REPO_REF=master \
--build-arg JM_SERVER_REPO_REF=master \
--tag "jam-serve-orderbook-standalone" ./standalone
```
- Checkout the branch `orderbook` for [PR#422](https://github.com/joinmarket-webui/joinmarket-webui/pull/422) in project `joinmarket-webui` and apply the following patch:
```patch
From b1a94581941cee920e90d314c141b150ad269244 Mon Sep 17 00:00:00 2001
From: theborakompanioni <theborakompanioni+github@gmail.com>
Date: Mon, 25 Jul 2022 14:56:12 -0600
Subject: [PATCH] dev: test …
```
=> feat: serve orderbook

standalone/Dockerfile, standalone/supervisor-conf/jmwalletd.conf, standalone/supervisor-conf/ob-watcher.conf
Uses `debian:bullseye-20220801-slim` instead of `python:3.9.10-slim-bullseye` as base image.
Every needed dependency is installed manually anyway. No functional changes.
This reduces the image size from 731MB to 669MB - still very bulky.
Also, downgrades `python` from `v3.9.10` to the debian repo version, which is `v3.9.2` at the time of writing.
Thinking about pinning all needed versions in a future PR, to adhere to reproducibility.
=> dev: use debian bullseye as image base

standalone/Dockerfile, standalone/supervisor-conf/tor.conf, standalone/torrc
Closes #60.
Before this PR the tor daemon ran as user `root`.
After this PR a distinct `tor` user is created and used to start the tor daemon.
Image of this branch is published and can be tested by pulling
`docker pull ghcr.io/joinmarket-webui/jam-dev-standalone:tor-user`
=> fix: run tor daemon with distinct user

readme.md, standalone/jam-entrypoint.sh
Fix for missing jm working directory if it is not mapped to the host system.
The log feature introduced a regression bug, when the logs moved from directory `$JM_WORK_DIR/logs` to `/var/log/jam`.
Since then, it was not ensured that the directory actually exists.
In most setups this is no problem, as the directory will most probably always be mapped to the host system via `--volume jmdatadir:/root/.joinmarket`, but in some situation, e.g. just starting the image once, this might lead to an error when the config file is copied: `cp: cannot create regular file '/root/.joinmarket/joinmarket.cfg': No such file or directory`.
The added line `mkdir --parents "${DATADIR}/"` now creates the directory in case it is missing.
Small additional change: In order to prevent supervisord from searching for …
=> fix: ensure jm working dir exists

standalone/Dockerfile
Hi!
mconfig scripts runs in a part of `make` command so we don't need to run that separately.
https://github.com/davmac314/dinit/blob/e679e6f50b43210863072e97d7f708c9fdb95dd0/Makefile#L30-L41
`Signed-off-by: Mobin Aydinfar <mobin@mobintestserver.ir>`
=> Remove unnecessary steps in building dinit

.github/workflows/check-and-update-dependencies.yml, .github/workflows/create-and-publish-docker-on-release.yml, .github/workflows/create-and-publish-docker.yml, .github/workflows/update-dependency-version.yml
Partly addresses #70.
These changes only affect github workflows. No changes to the image itself are made.
Warnings when building current `master` branch: https://github.com/joinmarket-webui/jam-docker/actions/runs/3298111040
Fixed (no more warnings) in this branch: https://github.com/joinmarket-webui/jam-docker/actions/runs/3297407397
=> deps(workflow): update github actions to newest versions

readme.md, standalone/Dockerfile, standalone/jam-entrypoint.sh
Resolves #75.
This PR enables waiting for the backing Bitcoin Core instance to be ready and accept RPC requests.
This is done by making a `getblockchaininfo` request before starting any services, as this is the first request JM will be performing during initialization. Also, as a by-product, the response is used to wait for `>= 100` blocks to be reported - thereby making the image `regtest`-compatible without further adaptions.
This behaviour can be disabled by setting env var `WAIT_FOR_BITCOIND` to `false`. Default value is `true`.
Please see this as a quick bugfix and not the final solution. Ideally, only service s`jmwalletd` and `ob-watcher` are waiting. Other services (such as `nginx` and `tor`) could already be started.
Please see https://github.com/joinmarket-webui/jam/pull/559 and …
=> feat: wait for bitcoind to accept RPC calls

standalone/default.cfg
Updates config property `directory_nodes` as per https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/ebdbac7e9855bedc2627fc5ad71630973901202d
=> config: recreate config according to JM v0.9.9

standalone/Dockerfile
See https://github.com/joinmarket-webui/jam/pull/585 and https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1396#issuecomment-1370536920 for more information.
This is required to successfully build JM `v0.9.9` - should not be needed as build arg `--docker-install` is used.. However, without it, it does not work and exits with:
```
Package python3-venv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python3-venv' has no installation candidate
Dependecies could not be installed. Exiting.
The command '/bin/bash -o pipefail -c ./install.sh --docker-install --without-qt     && rm --recursive --force install.sh deps/cache/ test/ .git/ .gitignore .github/ …
```
=> fix(build): install python3-venv

.github/workflows/check-and-update-dependencies.yml, .github/workflows/create-and-publish-docker-on-release.yml, .github/workflows/update-dependency-version.yml
Closes #70.
Closes #82.
Compare the two runs before and after the changes:
Before: https://github.com/joinmarket-webui/jam-docker/actions/runs/4003577079 (branch `master`)
After: https://github.com/joinmarket-webui/jam-docker/actions/runs/4006221672 (branch `fix/workflow-set-output`)
Deadline for merging this is [31st May, 2023](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
The deprecation warnings are fixed. However, if it _really_ works as expected, will only be known after a new JM or Jam release.
=> fix(actions): replace deprecated operations 

.github/workflows/update-dependency-version.yml
As hinted in https://github.com/joinmarket-webui/jam-docker/pull/92#issue-1556624322, whether fixing the deprecation warnings in #92 really worked, would only be known on a new Jam release. Well, it did not work correctly, as the output variables were written in a wrong format. This PR fixes the output patterns and makes the automatic version upgrade PRs function again.
=> fix(actions): proper usage of GITHUB_OUTPUT

standalone/Dockerfile
This PR updates [`dinit`](https://github.com/davmac314/dinit) from `v0.16.0` to `v0.16.1`.
See the changes here: https://github.com/davmac314/dinit/releases/tag/v0.16.1
=> build(deps): update dinit from v0.16.0 to v0.16.1

.env, readme.md, standalone/Dockerfile, ui-only/Dockerfile
Removes unneeded environment variables `JAM_REPO_BRANCH` and `JM_SERVER_REPO_BRANCH`.
I cannot remember exactly what the reasoning behind these additional variables was, but they seem redundant now as `--branch` arg of `git clone` can checkout branches as well as tags.
This should slightly speed up the initial repo checkout when building the images, albeit maybe unnoticeable.
=> build: simplify git repo checkout

standalone/default.cfg
Moves the `gaplimit` config variable from section `YIELDGENERATOR` to `POLICY` according to [joinmarket-clientserver#1525](https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1525).
Please only merge once the above PR is applied and/or a new JM version has been released.
=> chore(config): move 'gaplimit' to section 'POLICY'

readme.md, standalone/Dockerfile, ui-only/Dockerfile
- update `debian:bullseye` from `20221004` to `20230919`
- update `alpine` from `v3.16.2` to `v3.18.3`
- update `nginx` from `v1.23.1` to `v1.25.2`
=> build(deps): update base containers

standalone/Dockerfile, standalone/dinit-conf/jmwalletd, standalone/jam-entrypoint.sh
Update `dinit` from v0.16.1 to v0.18.0.
See https://github.com/davmac314/dinit/releases/tag/v0.18.0 for more information.
Log file permission handling has been slightly adapted. From the changelog (0.17.x):
> New service settings to control service logfile ownership and permissions: logfile-permissions, the logfile ownership and permissions are now always set).
Before, the default was to preserve the permissions on the log file if it already exists. Now, without the changes in this PR the `jmwalletd_stdout.log` file permissions would be `600`, making it non-readable for user `nginx`.
=> build(deps): update dinit from v0.16.1 to v0.18.0

standalone/nginx/default.conf
Resolves #123.
Increases the shared memory zone size from 64k to 256k.
This should fix problems reported by users on umbrelOS 1.x.
=> fix(nginx): increase upstreams shared memory size

standalone/Dockerfile, ui-only/Dockerfile
In order to fix the timeout issues in CI, this change adds the ability to specify the node version (and hence, the npm version) during the docker build. Newer npm versions should behave better during `npm install` and do not open as many connections as before, which might be the culprit on the timeouts in the CI builds.
Please build ui-only and standalone images and verify that everything is working as expected:
```shell
docker build --label "local" \
--build-arg JAM_REPO_REF=master \
--tag "joinmarket-webui/jam-ui-only" ./ui-only
```
```shell
docker build --label "local" \
--build-arg JAM_REPO_REF=master \
--build-arg JM_SERVER_REPO_REF=master \
--tag "joinmarket-webui/jam-standalone" ./standalone
```
=> build(docker): build with specific node version

standalone/Dockerfile, ui-only/Dockerfile
Pins the used base images, namely:
- `node:22.11.0-alpine@sha256:f265794478aa0b1a23d85a492c8311ed795bc527c3fe7e43453b3c872dcd71a3`
- `alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d`
- `debian:bullseye-20240926-slim@sha256:3f9e53602537cc817d96f0ebb131a39bdb16fa8b422137659a9a597e7e3853c1`
```shell
docker build --label "local" --build-arg JAM_REPO_REF=v0.3.0 --tag "joinmarket-webui/jam-ui-only" ./ui-only --no-cache
```
```shell
docker build --label "local" \
--build-arg JAM_REPO_REF=master \
--build-arg JM_SERVER_REPO_REF=master \
--tag "joinmarket-webui/jam-standalone" ./standalone --no-cache
```
=> build(docker): pin base image versions

justfile
```
$ just
Available recipes:
[development]
extract-default-config
[docker]
docker-build-standalone jam_repo_ref=env('JAM_REPO_REF') jm_server_repo_ref=env('JM_SERVER_REPO_REF') *args='' # create "standalone" docker image
docker-build-standalone-master *args='' # create "standalone" docker image from master
docker-build-ui jam_repo_ref=env('JAM_REPO_REF') *args='' # create "ui" docker image
docker-build-ui-master *args=''         # create "ui" docker image from master
docker-image-size                       # size of the docker images
docker-run-shell-standalone             # run shell in "standalone" docker container
[project-agnostic]
default                                 # print available targets
evaluate                                # evaluate and print all just variables …
```
=> chore(build): add justfile

justfile, standalone/default.cfg
Recreate default config from [current tip of `master` branch](https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/0e45c6991e678525085cf13a029f984ff04ae664).
Most importantly,  darkscience irc server is removed.
Also adapting directory nodes according to [list of directory nodes #1445](https://github.com/JoinMarket-Org/joinmarket-clientserver/issues/1445).
Most importantly, the default node `g3hv4uyn…` is removed and `ylegp63p…` added.
=> chore: recreate default config

standalone/Dockerfile
Build have been failing when using https as transport for the nginx repo.
Additionally the  nginx.org has been pinned.
=> fix: pin nginx repo

.github/workflows/check-and-update-dependencies.yml, .github/workflows/create-and-publish-docker-dev-manually.yml, .github/workflows/create-and-publish-docker-on-release.yml, .github/workflows/create-and-publish-docker.yml, .github/workflows/docker-contrib-dinit.yml, .github/workflows/update-dependency-version.yml, readme.md, standalone/jam-entrypoint.sh
Resolves #167.
Adds support for `rpc_cookie_file` param.
If env var `JM_RPC_COOKIE_FILE` is set, cookie authentication will be used. Otherwise, user/password authentication is used. The cookie file path should be accessible from within the container.
=> feat: support rpc_cookie_file
